version: "3.8"

networks:
  spring-network:
    driver: bridge

services:

  mysql-service:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: userManagementDb
      MYSQL_ROOT_PASSWORD: ashish@123
      MYSQL_USER: ashish
      MYSQL_PASSWORD: ashish@123
    #    ports:
    #      - "8082:3306"    removing port mapping since by default the 3306 will expose the functionality
    volumes:
      - ./src/main/resources/dockerizedEntireApp/init-script:/docker-entrypoint-initdb.d
#      - ./src/main/resources/dockerizedEntireApp/volumes/mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - entireApp
    networks:
      - spring-network

  mysql-service-onlyDb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: userManagementDb
      MYSQL_ROOT_PASSWORD: ashish@123
      MYSQL_USER: ashish
      MYSQL_PASSWORD: ashish@123
    ports:
        - "8082:3306"
    volumes:
      - ./src/main/resources/dockerizedEntireApp/init-script:/docker-entrypoint-initdb.d
#      - ./src/main/resources/dockerizedEntireApp/volumes/mysql_data:/var/lib/mysql
    profiles:
      - onlyDb
    networks:
      - spring-network

  adminer-service:
    image: adminer
    ports:
      - "8081:8080"
    profiles:
      - onlyDb
      - entireApp
    networks:
      - spring-network

  springApplication-service:
    build: .
    image: userserviceimage:v1
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql-service:3306/userManagementDb?useSSL=false&allowPublicKeyRetrieval=true"
    depends_on:
      - mysql-service
    profiles:
      - entireApp
    networks:
      - spring-network