version: "3.0"

services:

  mysql-service:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: userManagementDb
      MYSQL_ROOT_PASSWORD: ashish@123
      MYSQL_USER: ashish
      MYSQL_PASSWORD: ashish@123
#    ports:
#      - "8082:3306"    removing port mapping since by default the 3306 will expose the functionality
    volumes:
      - ./src/main/resources/dockerizedEntireApp/init-script:/docker-entrypoint-initdb.d
      - ./src/main/resources/dockerizedEntireApp/volumes/mysql_data:/var/lib/mysql

  adminer-service:
      image: adminer
      restart: always
      ports:
        - "8081:8080"

  springApplication-service:
    build: .
    image: userserviceimage:v1
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql-service:3306/userManagementDb?useSSL=false&allowPublicKeyRetrieval=true"
    depends_on:
      - mysql-service